version: "3"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "6305:3306"
  api:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "4000:3000"
    volumes:
      - ".:/todo-server-rails"
      - bundle:/usr/local/bundle
      - rails_cache:/todo-server-rails/tmp/cache
    depends_on:
      - db
    command: bash -c "bundle install && rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
volumes:
  bundle:
    driver: local
  db_data:
    driver: local
  rails_cache:
